---
output:
  pdf_document: default
  html_document: default
---
# Series and Sequence

Reading Materials: \newline
Croft, A. and R. Davidson *Foundation maths.* (Harlow: Pearson, 2016) 6th edition. **Chapter 12 Sequences and series.**

## Little Gauss

*Skip this section if you have no interest in casual reading.*



\noindent There is this story that is often told in mathematics classes. While the story itself is likely apocryphal, it likely have some pedagogical value. The story goes this way:



\noindent There was once a German school where a boy Carl Friedrich made mischief during mathematics lesson. Instead of corporal punishment that was common in that time, the teacher instead decided to give him mathematics assignment to keep him busy. He was asked to add up the numbers from one to a hundred. Most students would diligently start adding and be busy for a while. The young Carl Friedrich, on the other hand, answered after a few minutes. The teacher was surprised at the request to speak, since he had just kept the boy busy. He was all the more astonished when Carl Friedrich said that he had finished the task and was even able to say the correct result (5050).



**How had he solved it?**



\noindent How he did it so fast? Carl Friedrich discovered discovered the following - unfortunately I do not know what coincidence was behind it. He wrote the numbers down like this:

| 1   | 2  | 3  | $\dots$ | 99 | 100 |
|:---:|:---:|:---:|:---------------:|:---:|:---:|
| 100 | 99 | 98 | $\dots$ | 2  | 1   |

\noindent This still doesn't look interesting yet. He would then add up the numbers.

| 1   | 2   | 3   | $\dots$ | 99  | 100 |
|:---:|:---:|:---:|:---------------:|:---:|:---:|
| 100 | 99  | 98  | $\dots$ | 2   | 1   |
| 101 | 101 | 101 | $\dots$ | 101 | 101 |

\noindent Each of them have the sum 101. This looks rather promising. 

 

\noindent To sum it up, we write down the numbers from one to one hundred twice, once in increasing order and once in decreasing order, we would then sum them up and we can clearly see that we obtain the sum of $100 \cdot 101$. But we are not finished yet because we counted each numbers twice so we still have to divide the results by two. Then, we would have the sum of numbers from one to a hundred. And that's exactly how Carl Friedrich proceeded. Do we know Carl Friedrich? Hopefully that's the case, because Carl Friedrich was none other than Carl Friedrich Gauss. One of the most important German mathematicians (if not the most important German mathematician).



**Let us talk about the formula**



\noindent Mathematicians love formulas or should I say the general solution of a problem. The sum of the first $n$ of natural numbers follows the formula:
\begin{equation}
	\Sigma = \frac{n\cdot(n+1)}{2}
\end{equation}
\noindent This is not as complicated as it looks. We could for example count the sum of 1 to 150, then we set $n$ equals to 150.
\begin{equation}
	\Sigma = \frac{150\cdot(150+1)}{2}= \frac{150\cdot(151)}{2}= \frac{22650}{2}=11325
\end{equation}
\noindent This formula is today is still affectionately referred as "Der Kleine Gauss", German for "Little Gauss". Anyone studying higher mathematics would have to prove the validity of the formula. The formula itself is an arithmetic series. We would learn more about it later.

## Sequence

A sequence is a set of numbers written down in a specific order. For example, 1,3,4,7,9. There need not be an obvious rule relating to the numbers in the sequence. For example, 9, -11, $\frac{1}{2}$, 32.5 is a sequence.\newline
A simple way of forming a sequence is to calculate each new term by adding a fixed amount to the previous term. For example, $1,7,13,19, \dots$.\newline
Such sequence is called arithmetic progression or arithmetic sequence.

\vspace{5mm}

\noindent Geometric progression is a sequence formed by multiplying the previous term by fixed amount. For example, $2,10,50, 250,\dots$.

\vspace{5mm}

\noindent Some sequences continue indefinitely, these are called infinite sequences/ It can happen that as we move along the sequence, the term get closer and closer to a fixed value. For example, $1,\frac{1}{2},\frac{1}{3},\frac{1}{4},\frac{1}{5}, \dots$.\newline
This sequence can be rewritten in the form of:

\begin{equation}\label{eq3}
	x_k = \frac{1}{k} \text{ , for } k = 1, 2,3,4,5,\dots
\end{equation}

\noindent As $k$ get larger and larger, and approaches infinity, $x_k$ get closer and closer to zero. We say that *$\frac{1}{k}$ tends to zero as $k$ tends to infinity* or alternatively, *as k tends to infinity, the limit of the sequence is zero*. We write this down as:
\begin{equation}\label{eq4}
\lim_{k \to \infty} \frac{1}{k} = 0
\end{equation}
\noindent When a sequence possess a limit, it is said to *converge*, when not, it is said to *diverge*.

## Series

\noindent If the terms of a sequence are added the result is known as series. A series is a sum. If the series contains a finite number of terms, we are able to add them all up and obtain the sum.\newline

\vspace{5mm}

\noindent A series is said to *converge* if it has finite sum.

\vspace{5mm}

\noindent The sum of first $n$ terms of an arithmetic series with first term $a$ and common difference $d$ is denoted by $S-n$ and given by
\begin{equation}\label{eq5}
S_n = \frac{n}{2}(2a+(n-1)d)
\end{equation}
\noindent The sum of first $n$ terms of an geometric series with first term $a$ and common ratio $r$ is denoted by $S-n$ and given by
\begin{equation}\label{eq6}
S_n = \frac{a(1-r^n)}{1-r} \text{ , for } r \neq 1
\end{equation}
\noindent for $n \to \infty$ and $-1<r<1$,
\begin{equation}\label{eq7}
S_n = \frac{a}{1-r}
\end{equation}

\noindent Beware that a converging sequence does not mean it's sum (series) converges. In our example of $x_k = \frac{1}{k}$, $x$ converges to zero as $k$ approaches infinity however, the sum of $x$ does not. This is known as *Harmonic series*. I'm not going to prove it here. You can check yourself [here](https://proofwiki.org/wiki/Harmonic_Series_is_Divergent).