--- 
title: "CM 1015 Computational Mathematics"
author: "Kevin Juandi"
date: "`r Sys.Date()`"
output: 
  bookdown::gitbook
  bookdown::pdf_book
documentclass: book
bibliography:
- book.bib
- packages.bib
link-citations: yes
github-repo: "rstudio/bookdown-demo"
colorlinks: true
knit: "bookdown::render_book"
site: "bookdown::bookdown_site"
---

# Preface {-}

I wrote this note after finishing the course, so the content might not reflect the current version of the course. It is mostly based on my handwritten personal notes. I personally feel this course should be called "Foundation Mathematics" instead of "Computational Mathematics" because of the lack of "Numerical Methods" and probably some other things people more familiar with the topic would say. If you spot any error please don't hesitate to contact me via slack or mail me.

<!--chapter:end:index.Rmd-->

---
output:
  pdf_document: default
  html_document: default
---
# Number Bases, Conversion and Operations
\newcommand*{\carry}[1][1]{\overset{#1}}
Reading Materials: \newline
Croft, A. and R. Davidson *Foundation maths.* (Harlow: Pearson, 2016) 6th edition. **Chapter 14 Number Bases**

## Number Bases

**Decimal System**

The numbers that we commonly used are based on 10.\newline
For example:
\begin{equation} \label{eq1}
\begin{split}
253 & = 200 + 50 + 3 \\
& = 2(100) + 5(10) + 3 \\
& = 2(10^2)+ 5(10^1) + 3(10^0)
\end{split}
\end{equation} 

**Binary System**

\normalsize A binary system uses base 2, it only consist of 2 digits, 0 and 1.\newline
Numbers in base 2 are called binary digits or simply bits.\newline
Consider the binary number $110101_2$. As the base is 2, this means that power of 2 essentially replace powers of 10. Let us convert it to base 10.
\begin{equation} \label{eq2}
\begin{split}
110101_2 & = 1(2^5)+1(2^4)+0(2^3)+1(2^2)+0(2^1)+1(2^0) \\
& = 1(32)+1(16)+0(8)+1(4)+0(2)+1(1) \\
& = 32+16+4+1 \\
& = 53_{10}
\end{split}
\end{equation} 

**Octal System**

\normalsize Octal numbers use 8 as a base. The eight digits used in the octal system are 0, 1, 2, 3, 4, 5, 6 and 7. Octal numbers use powers of 8, just as decimal numbers use powers of 10 and binary numbers use powers of 2. Example:
\begin{equation} \label{eq3}
\begin{split}
325_8 & = 3(8^2)+2(8^1)+5(8^0) \\
& = 3(64)+2(8)+5(1) \\
& = 192+16+5 \\
& = 213_{10}
\end{split}
\end{equation} 

**Hexadecimal System**

\normalsize Hexadecimal system use 16 as a base. The digits are 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E and F. Example:
\begin{equation} \label{eq4}
\begin{split}
93\text{A}_{16} & = 9(16^2)+3(16^1)+\text{A}(16^0) \\
& = 9(256)+3(16)+10(1) \\
& = 2304+48+10 \\
& = 2362_{10}
\end{split}
\end{equation} 

## Number Conversion

### Converting from Decimal to Other Number Base

\noindent The no-brainer way is to divide the number by the base, the remainder would be the last digit of the new number base. Keep dividing the quotient until it is smaller than the number base. Let us convert $253_{10}$ as example.
\begin{equation} \label{eq5}
\begin{split}
2{\overline{\smash{\big)}\,253\phantom{)}}} & = 126 \text{ with remainder }1\\
2{\overline{\smash{\big)}\,126\phantom{)}}} & = 63 \text{ with remainder }0\\
2{\overline{\smash{\big)}\,63\phantom{)}}} & = 31 \text{ with remainder }1\\
2{\overline{\smash{\big)}\,31\phantom{)}}} & = 15 \text{ with remainder }1\\
2{\overline{\smash{\big)}\,15\phantom{)}}} & = 7 \text{ with remainder }1\\
2{\overline{\smash{\big)}\,7\phantom{)}}} & = 3 \text{ with remainder }1\\
2{\overline{\smash{\big)}\,3\phantom{)}}} & = 1 \text{ with remainder }1\\
2{\overline{\smash{\big)}\,1\phantom{)}}} & = 0 \text{ with remainder }1
\end{split}
\end{equation} 
Thus, $253_{10}$ is $11111101_2$ in binary. We could do the same to other number bases. \newline
Another method is by listing the powers of the base, compare and subtract. Using the same number as example.

| $2^0 = 1$  | $2^1 = 2$   | $2^2 = 4$   |
|:----------:|:-----------:|:-----------:|
| $2^3 = 8$  | $2^4 = 16$  | $2^5 = 32$  |
| $2^6 = 64$ | $2^7 = 128$ | $2^8 = 256$ |

From here we compare the number that we are going to convert with the list:
\begin{equation} \label{eq6}
\begin{split}
253 - 1(128) & = 125  \\
125 - 1(64) & = 61 \\
61 - 1(32) & = 29 \\ 
29 - 1(16) & = 13 \\
13 - 1(8) & = 5 \\
5 - 1(4) & = 1 \\
1 - 0(2) & = 1\\
1- 1(1) & = 0
\end{split}
\end{equation} 
Thus, $253_{10}$ is $11111101_2$ in binary. Like the other method, we can also do this to convert to other number bases.

### Conversion with Binary Number

\noindent Converting binary numbers to Octal or Hexadecimal and vice versa are very straightforward. It can be performed without converting to Decimal first. Let us use number $11100110_2$ as example:
\begin{equation} \label{eq7}
\begin{split}
\underbrace{11}_\text{3}\underbrace{100}_\text{4}\underbrace{110}_\text{6} & = 346_8\\
\underbrace{1110}_\text{E}\underbrace{0110}_\text{6} & = \text{E}6_{16}
\end{split}
\end{equation}
\subsection{Non-integer Number Conversion}
Converting non-integer number might look counterintuitive and intimidating. It is actually rather simple. Let us convert $17.375_{10}$ to binary.
\[\begin{split}
17.375 & = 10 + 7 + 0.3+0.07+0.005 \\
& = 1(10^1) + 7(10^0) + 3(10^{-1}) + 7(10^{-2})+5(10^{-3})
\end{split}\]
Converting to binary, $17_{10} = 10001_2$. But how about the decimal point?
We multiply them by two until we are left with whole number
\begin{equation} \label{eq8}
\begin{split}
0.375 \times 2  = 0.75 = 0+0.75 & \text{ we have 0 at power }-1\\
0.75 \times 2  = 1.5 = 1+0.5 & \text{ we have 1 at power }-2\\
0.5 \times 2  = 1.0 = 1 & \text{ we have 1 at power }-3
\end{split}
\end{equation} 
Thus, $17.375_{10} = 10001.011_2$\newline
The reverse is much simpler.
\begin{equation} \label{eq9}
\begin{split}
1101.101_2 & = 1(2^3)+1(2^2)+0(2^1)+1(2^0)+1(2^{-1})+0(2^{-2})+1(2^{-3}) \\
& = 1(8)+1(4)+0(2)+1(1)+1(0.5)+0(0.25)+1(0.125) \\
& = 8 + 4 + 1+ 0.5+0.125 \\
& = 13.625_{10}
\end{split}
\end{equation} 

### Operations with Binary Number

**Addition**

\normalsize Addition is rather straightforward, just like with decimal numbers. Here we use $11001001_2$ and $11111111_2$ as example. In decimal they are 201 and 255 respectively.
\begin{equation}\label{eq10}
	\begin{array}{B3}
		\carry 0 & \carry 1\carry 1\carry 0\carry 0 & \carry 1\carry 0\carry 01 \\
		{} + 0 &                             1111 &                      1111\\ \hline
		1 &                             1100 &                      1000\\
	\end{array}
\end{equation}
\begin{equation} \label{eq11}
\underbrace{11001001}_\text{201}+\underbrace{11111111}_\text{255} = \underbrace{1 1100 1000}_\text{456}
\end{equation}

**Subtraction**

\normalsize Likewise for subtraction, between $111 0011_2$ and $101 0010_2$
\begin{equation}\label{eq12}
	\begin{array}{B3}
		 1  1 1 &  0 0 11\\
		{} -                              101 &                      0010\\ 
		\hline
		010 &                      0001 \\
	\end{array}
\end{equation}
\begin{equation} \label{eq13}
	\underbrace{1110011}_\text{115}-\underbrace{1010010}_\text{82} = \underbrace{100001}_\text{33}
\end{equation}

**Multiplication**

\normalsize Multiplication is essentially addition done multiple times. Let us have multiplication of $1100_2$ and $1111_2$. I would skip the carry so it wouldn't look too cramped.
\begin{equation}\label{eq14}
	\begin{array}{c}
		\phantom{\times9999}1100\\
		\underline{\times\phantom{9999}1111}\\
		\phantom{\times9999}1100\\
		\phantom{\times999}1100\phantom9\\
		\phantom{\times99}1100\phantom{99}\\
		\underline{\phantom{\times9}1100\phantom{999}}\\
		\phantom\times10110100
	\end{array}
\end{equation}
\begin{equation} \label{eq15}
	\underbrace{1100}_\text{12}\times\underbrace{1111}_\text{15} = \underbrace{10110100}_\text{180}
\end{equation}

**Division**

\normalsize Division is perhaps the one that feels the most unnatural and most likely to cause mistakes. Let us do this with $11100110_2$ divided with $110_2$ as example.
\begin{equation}\label{eq16}
\begin{array}{r}
100110\phantom{)}   \\
110{\overline{\smash{\big)}\,11100110\phantom{)}}}\\
\underline{-~\phantom{(}110\phantom{99999)}}\\
\phantom{\times{99}}10\phantom{9999)}\\ 
\underline{-~\phantom{()}0\phantom{9999)}}\\ 
\phantom{\times{99}}100\phantom{999)}\\ 
\underline{-~\phantom{()}0\phantom{999)}}\\ 
\phantom{\times{99}}1001\phantom{99)}\\ 
\underline{-~\phantom{()}110\phantom{99)}}\\ 
\phantom{\times{999}}111\phantom{9)}\\ 
\underline{-~\phantom{()}110\phantom{9)}}\\
\phantom{\times{9999}}10\phantom{)}\\ 
\underline{-~\phantom{()}0\phantom{)}}\\  
10\phantom{)}
\end{array}
\end{equation}

\begin{equation} \label{eq17}
	\underbrace{11100110}_\text{230}\div\underbrace{110}_\text{12} = \underbrace{100110}_\text{38} \text{ with remainder }\underbrace{10}_\text{2}
\end{equation}

<!--chapter:end:01-number-bases.Rmd-->

---
output:
  pdf_document: default
  html_document: default
---
# Series and Sequence

Reading Materials: \newline
Croft, A. and R. Davidson *Foundation maths.* (Harlow: Pearson, 2016) 6th edition. **Chapter 12 Sequences and series.**

## Little Gauss

*Skip this section if you have no interest in casual reading.*



\noindent There is this story that is often told in mathematics classes. While the story itself is likely apocryphal, it likely have some pedagogical value. The story goes this way:



\noindent There was once a German school where a boy Carl Friedrich made mischief during mathematics lesson. Instead of corporal punishment that was common in that time, the teacher instead decided to give him mathematics assignment to keep him busy. He was asked to add up the numbers from one to a hundred. Most students would diligently start adding and be busy for a while. The young Carl Friedrich, on the other hand, answered after a few minutes. The teacher was surprised at the request to speak, since he had just kept the boy busy. He was all the more astonished when Carl Friedrich said that he had finished the task and was even able to say the correct result (5050).



**How had he solved it?**



\noindent How he did it so fast? Carl Friedrich discovered discovered the following - unfortunately I do not know what coincidence was behind it. He wrote the numbers down like this:

| 1   | 2  | 3  | $\dots$ | 99 | 100 |
|:---:|:---:|:---:|:---------------:|:---:|:---:|
| 100 | 99 | 98 | $\dots$ | 2  | 1   |

\noindent This still doesn't look interesting yet. He would then add up the numbers.

| 1   | 2   | 3   | $\dots$ | 99  | 100 |
|:---:|:---:|:---:|:---------------:|:---:|:---:|
| 100 | 99  | 98  | $\dots$ | 2   | 1   |
| 101 | 101 | 101 | $\dots$ | 101 | 101 |

\noindent Each of them have the sum 101. This looks rather promising. 

 

\noindent To sum it up, we write down the numbers from one to one hundred twice, once in increasing order and once in decreasing order, we would then sum them up and we can clearly see that we obtain the sum of $100 \cdot 101$. But we are not finished yet because we counted each numbers twice so we still have to divide the results by two. Then, we would have the sum of numbers from one to a hundred. And that's exactly how Carl Friedrich proceeded. Do we know Carl Friedrich? Hopefully that's the case, because Carl Friedrich was none other than Carl Friedrich Gauss. One of the most important German mathematicians (if not the most important German mathematician).



**Let us talk about the formula**



\noindent Mathematicians love formulas or should I say the general solution of a problem. The sum of the first $n$ of natural numbers follows the formula:
\begin{equation}
	\Sigma = \frac{n\cdot(n+1)}{2}
\end{equation}
\noindent This is not as complicated as it looks. We could for example count the sum of 1 to 150, then we set $n$ equals to 150.
\begin{equation}
	\Sigma = \frac{150\cdot(150+1)}{2}= \frac{150\cdot(151)}{2}= \frac{22650}{2}=11325
\end{equation}
\noindent This formula is today is still affectionately referred as "Der Kleine Gauss", German for "Little Gauss". Anyone studying higher mathematics would have to prove the validity of the formula. The formula itself is an arithmetic series. We would learn more about it later.

## Sequence

A sequence is a set of numbers written down in a specific order. For example, 1,3,4,7,9. There need not be an obvious rule relating to the numbers in the sequence. For example, 9, -11, $\frac{1}{2}$, 32.5 is a sequence.\newline
A simple way of forming a sequence is to calculate each new term by adding a fixed amount to the previous term. For example, $1,7,13,19, \dots$.\newline
Such sequence is called arithmetic progression or arithmetic sequence.

\vspace{5mm}

\noindent Geometric progression is a sequence formed by multiplying the previous term by fixed amount. For example, $2,10,50, 250,\dots$.

\vspace{5mm}

\noindent Some sequences continue indefinitely, these are called infinite sequences/ It can happen that as we move along the sequence, the term get closer and closer to a fixed value. For example, $1,\frac{1}{2},\frac{1}{3},\frac{1}{4},\frac{1}{5}, \dots$.\newline
This sequence can be rewritten in the form of:

\begin{equation}\label{eq3}
	x_k = \frac{1}{k} \text{ , for } k = 1, 2,3,4,5,\dots
\end{equation}

\noindent As $k$ get larger and larger, and approaches infinity, $x_k$ get closer and closer to zero. We say that *$\frac{1}{k}$ tends to zero as $k$ tends to infinity* or alternatively, *as k tends to infinity, the limit of the sequence is zero*. We write this down as:
\begin{equation}\label{eq4}
\lim_{k \to \infty} \frac{1}{k} = 0
\end{equation}
\noindent When a sequence possess a limit, it is said to *converge*, when not, it is said to *diverge*.

## Series

\noindent If the terms of a sequence are added the result is known as series. A series is a sum. If the series contains a finite number of terms, we are able to add them all up and obtain the sum.\newline

\vspace{5mm}

\noindent A series is said to *converge* if it has finite sum.

\vspace{5mm}

\noindent The sum of first $n$ terms of an arithmetic series with first term $a$ and common difference $d$ is denoted by $S-n$ and given by
\begin{equation}\label{eq5}
S_n = \frac{n}{2}(2a+(n-1)d)
\end{equation}
\noindent The sum of first $n$ terms of an geometric series with first term $a$ and common ratio $r$ is denoted by $S-n$ and given by
\begin{equation}\label{eq6}
S_n = \frac{a(1-r^n)}{1-r} \text{ , for } r \neq 1
\end{equation}
\noindent for $n \to \infty$ and $-1<r<1$,
\begin{equation}\label{eq7}
S_n = \frac{a}{1-r}
\end{equation}

\noindent Beware that a converging sequence does not mean it's sum (series) converges. In our example of $x_k = \frac{1}{k}$, $x$ converges to zero as $k$ approaches infinity however, the sum of $x$ does not. This is known as *Harmonic series*. I'm not going to prove it here. You can check yourself [here](https://proofwiki.org/wiki/Harmonic_Series_is_Divergent).

<!--chapter:end:02-series-and-sequence.Rmd-->

---
output:
  pdf_document: default
  html_document: default
---
# Modular Arithmetic

Reading Materials: \newline
Yan, S.Y. *Number theory for computing.* (Berlin: Springer-Verlag, 2002) 2nd edition. **Section 1.2 Theory of divisibility pp.21-pp.24 , Section 1.6 Theory of congruences pp.111-119**

## Congruence

\noindent Modular arithmetic is a system of arithmetic for integers where the number "wraps around" after reaching a certain value we call **modulus**



\noindent Modular arithmetic is commonly used in number theory, algebra (group theory, ring theory, etc) and also in cryptography. An example in daily life is the clock. The numbers go from 1 to 12, but when you get to "13 o'clock", it actually becomes 1 o'clock again (think of how the 24 hour clock numbering works). So 13 becomes 1, 14 becomes 2, and so on. This can keep going, so when you get to "25 o'clock'', you are actually back round to where 1 o'clock is on the clock face (and also where 13 o'clock was too), this is arithmetic modulo 12.



\noindent In our clock example, the number go from 1 to 12. In formal mathematics, we usually start from 0. In this case our clock would have 12 replaced with zero. Thus,
\begin{equation}
24\equiv 0 \mod{12}
\end{equation}
\noindent Two integers $a$ and $b$ are said to be **congruent** modulus $k$ if when they are divided by $k$, they have the same remainder.

\noindent More examples:
\begin{equation}
\begin{split}
3 &\equiv 5 \mod{2} 
\end{split}
\end{equation}
3 divided by 2 gives 1 with remainder 1, 5 divided by 2 gives 2 with remainder 1.
\begin{equation}
\begin{split}
14 &\equiv 2 \mod{12} 
\end{split}
\end{equation}
14 divided by 12 gives 1 with remainder 2, 2 divided by 12 gives 0 with remainder 2.


\noindent How about negative numbers? $-17 \mod{12} $ for example:
\begin{equation}
\begin{split}
-17 \mod{12} & \equiv -5\mod{12}\\
 & \equiv 7 \mod{12}
\end{split}
\end{equation}

## Operations in Modular Arithmetics

Examples in modulus 12:
\begin{equation}
	\begin{split}
		14+28\equiv 2+4 \equiv 6 & \rightarrow 14+28 \equiv 6\mod{12}\\
		28-14\equiv 4-2 \equiv 2 & \rightarrow 28-14 \equiv 2\mod{12}\\
		11+28\equiv 11+4 \equiv 15 \equiv 3 & \rightarrow 11+28 \equiv 3\mod{12}\\
		14\times28\equiv 2\times4 \equiv 8 & \rightarrow 14\times28 \equiv 8\mod{12}\\
	\end{split}
\end{equation}
Division can not be straightforwardly extended. For example, $4\div 12$ is not defined since $12\equiv 0 \mod 12$. We should first define multiplicative inverse of $\mod k$.


\noindent Multiplicative inverse $m^{-1}$ of integer $m$ is defined as:
\begin{equation}
	m\times m^{-1} = 1 \mod k
\end{equation}
Then we define $a\div b$ in $\mod k$ as multiplication of $a\times b^{-1}$. For example:
\begin{equation}
	\begin{split}
		2^{-1} \mod 7 & \\
		2 \times 4 \equiv 1 \mod 7 & \rightarrow 2^{-1} \mod 7 = 4 \mod 7
	\end{split}
\end{equation}
Division example:
\begin{equation}
6 \div 2 \mod 7 \equiv 6 \times 2^{-1} \equiv 6\times 4 \equiv 24 \equiv 3 \mod 7
\end{equation}
Inverse don't always exist, for example, the inverse of $2 \mod 4$

<!--chapter:end:03-modular-arithmetic.Rmd-->

